export const THREE_D_MODE_CONFIG = {
  scene: {
    exposure: 1.02,
    mobileExposure: 1.02,
    bloomStrength: 0.58,
    bloomRadius: 0.3,
    bloomThreshold: 0.86,
    mobileBloomStrength: 0.58,
    mobileBloomRadius: 0.3,
    mobileBloomThreshold: 0.86,
    cameraFov: 45,
    mobileCameraFov: 56,
    cameraPosition: { x: 8.4, y: 5.4, z: 10.8 },
    mobileCameraPosition: { x: 8.8, y: 5.8, z: 13.2 },
    orbitTarget: { x: 0, y: 0.25, z: 0 },
    mobileOrbitTarget: { x: 0, y: 0.15, z: 0 },
    minDistance: 2.3,
    maxDistance: 28,
    maxPolarAngle: Math.PI * 0.88,
  },
  lights: {
    ambient: 0.32,
    hemisphere: 1.65,
    key: 2.15,
    rim: 0.95,
  },
  grid: {
    opacity: 0.13,
    mobileOpacity: 0.13,
    floorGlowOpacity: 0.075,
    mobileFloorGlowOpacity: 0.075,
  },
  model: {
    emissiveBase: 1,
    emissiveMax: 1.5,
    emissivePulse: 0.42,
    opticalTableColor: 0xa8b4be,
    opticalTableRoughness: 1,
    opticalTableMetalness: 0,
    opticalTableEmissiveIntensity: 0,
    opticalTableToneMapped: false,
    laserBeamIntensity: 0.58,
    laserBeamGlowOpacity: 0.42,
    laserEmitterIntensity: 0.18,
    laserEmitterGlowOpacity: 0.08,
    laserEmitterColor: 0xd2dbe4,
    bboIntensity: 0.46,
    bboGlowOpacity: 0.44,
    photonPathIntensity: 0.82,
    detectorGlowIntensity: 0.86,
    bboInternalLightMaxIntensity: 900,
  },
  effects: {
    particleOpacity: 0.68,
    mobileParticleOpacity: 0.68,
    lowParticleOpacity: 0.68,
    trailOpacity: 0.76,
    pumpBeamOpacity: 0.16,
    laserBeamIntensity: 0.62,
    laserBeamGlowOpacity: 0.16,
    laserBeamRadiusScale: 0.68,
    laserBeamMaxOpacity: 0.32,
    entangledBeamAOpacity: 0.24,
    entangledBeamBOpacity: 0.23,
    bboAuraOpacity: 0.055,
    bboGlowOpacity: 0.06,
    bboPulseOpacity: 0.14,
    bboPulseRadiusScale: 0.7,
    bboAuraRadiusScale: 0.72,
    bboPulseLightIntensity: 1.1,
    pulseMaxOpacity: 0.16,
  },
  low: {
    exposure: 0.72,
    bloomStrength: 0.08,
    bloomRadius: 0.12,
    bloomThreshold: 0.94,
  },
};

export const VR_MODE_CONFIG = {
  ...THREE_D_MODE_CONFIG,
  scene: {
    ...THREE_D_MODE_CONFIG.scene,
    exposure: 0.88,
    mobileExposure: 0.88,
    bloomStrength: 0.46,
    mobileBloomStrength: 0.46,
    bloomRadius: 0.28,
    mobileBloomRadius: 0.28,
    bloomThreshold: 0.89,
    mobileBloomThreshold: 0.89,
    cameraFov: 58,
    mobileCameraFov: 58,
    cameraPosition: { x: 1.1, y: 1.25, z: 4.2 },
    mobileCameraPosition: { x: 2.2, y: 1.65, z: 5.4 },
    orbitTarget: { x: 0.4, y: 0.6, z: 0 },
    mobileOrbitTarget: { x: 0.1, y: 0.45, z: 0 },
    minDistance: 0.6,
    maxDistance: 18,
  },
  lights: {
    ...THREE_D_MODE_CONFIG.lights,
    hemisphere: 1.5,
    key: 1.85,
  },
  model: {
    ...THREE_D_MODE_CONFIG.model,
    opticalTableColor: 0xa8b4be,
    opticalTableRoughness: 1,
    opticalTableMetalness: 0,
    opticalTableEmissiveIntensity: 0,
    opticalTableToneMapped: false,
    bboInternalLightMaxIntensity: 900,
  },
  vr: {
    eyeHeight: 1.35,
  },
};

export const AR_MODE_CONFIG = {
  source: 'src/pages/ar/arConfig.js',
  note: 'AR uses its own MindAR low-brightness and calibration visual parameters.',
};

// Backward-compatible alias for shared modules that do not care about the route.
export const VISUAL_CONFIG = {
  ...THREE_D_MODE_CONFIG,
  vr: VR_MODE_CONFIG.vr,
};
